// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: proto/marvin.proto

package marvin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarvinService_Connect_FullMethodName = "/marvin.MarvinService/Connect"
)

// MarvinServiceClient is the client API for MarvinService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarvinServiceClient interface {
	// Bi-directional stream for Marvin agent to connect to control plane.
	// Lifecycle:
	//  1. Marvin sends Register (once)
	//  2. Control plane responds with Registered or RegistrationRejected
	//  3. Marvin sends periodic Heartbeat
	//  4. Control plane sends ExecuteCapability, Disconnect, or UpdateConfig
	//  5. Marvin sends CapabilityResult, LogEvent, StatusUpdate
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControlMessage], error)
}

type marvinServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarvinServiceClient(cc grpc.ClientConnInterface) MarvinServiceClient {
	return &marvinServiceClient{cc}
}

func (c *marvinServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarvinService_ServiceDesc.Streams[0], MarvinService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarvinService_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ControlMessage]

// MarvinServiceServer is the server API for MarvinService service.
// All implementations must embed UnimplementedMarvinServiceServer
// for forward compatibility.
type MarvinServiceServer interface {
	// Bi-directional stream for Marvin agent to connect to control plane.
	// Lifecycle:
	//  1. Marvin sends Register (once)
	//  2. Control plane responds with Registered or RegistrationRejected
	//  3. Marvin sends periodic Heartbeat
	//  4. Control plane sends ExecuteCapability, Disconnect, or UpdateConfig
	//  5. Marvin sends CapabilityResult, LogEvent, StatusUpdate
	Connect(grpc.BidiStreamingServer[AgentMessage, ControlMessage]) error
	mustEmbedUnimplementedMarvinServiceServer()
}

// UnimplementedMarvinServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarvinServiceServer struct{}

func (UnimplementedMarvinServiceServer) Connect(grpc.BidiStreamingServer[AgentMessage, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedMarvinServiceServer) mustEmbedUnimplementedMarvinServiceServer() {}
func (UnimplementedMarvinServiceServer) testEmbeddedByValue()                       {}

// UnsafeMarvinServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarvinServiceServer will
// result in compilation errors.
type UnsafeMarvinServiceServer interface {
	mustEmbedUnimplementedMarvinServiceServer()
}

func RegisterMarvinServiceServer(s grpc.ServiceRegistrar, srv MarvinServiceServer) {
	// If the following call panics, it indicates UnimplementedMarvinServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarvinService_ServiceDesc, srv)
}

func _MarvinService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MarvinServiceServer).Connect(&grpc.GenericServerStream[AgentMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarvinService_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ControlMessage]

// MarvinService_ServiceDesc is the grpc.ServiceDesc for MarvinService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarvinService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marvin.MarvinService",
	HandlerType: (*MarvinServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _MarvinService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/marvin.proto",
}
