package testutil

// ScramConfig holds the credentials used to authenticate against a Kafka
// broker that has SCRAM-SHA-256 enabled on its client-facing listener.
//
// The StartKafkaWithSCRAM helper provisions a single SCRAM user with these
// exact credentials (admin / admin-secret) via `kafka-storage format
// --add-scram`, so callers can rely on them being present.
type ScramConfig struct {
	// Username is the SCRAM principal name (e.g. "admin").
	Username string
	// Password is the SCRAM principal password (e.g. "admin-secret").
	Password string
}

// TLSConfig describes the client-side TLS material required to connect to a
// Kafka broker that has mTLS (mutual TLS) enabled. All three paths point at
// PEM-encoded files generated by StartKafkaWithMTLS.
type TLSConfig struct {
	// CAPath is the path to the PEM-encoded CA certificate used to sign both
	// the server and client certificates.
	CAPath string
	// CertPath is the path to the PEM-encoded client certificate.
	CertPath string
	// KeyPath is the path to the PEM-encoded client private key.
	KeyPath string
}

// CertPaths mirrors TLSConfig but is returned separately by
// StartKafkaWithMTLS so callers that only need the raw file locations (for
// example to build a *tls.Config) can do so without parsing the TLSConfig
// struct. It is kept distinct for API clarity.
type CertPaths struct {
	// CAPath is the path to the PEM-encoded CA certificate.
	CAPath string
	// CertPath is the path to the PEM-encoded client certificate.
	CertPath string
	// KeyPath is the path to the PEM-encoded client private key.
	KeyPath string
}

// KerberosConfig describes the Kerberos realm and service principal that the
// Kafka broker is configured to use for GSSAPI authentication.
type KerberosConfig struct {
	// Realm is the Kerberos realm (e.g. "EXAMPLE.COM").
	Realm string
	// KDC is the hostname of the KDC container on the shared Docker network
	// (e.g. "kdc").
	KDC string
	// ServiceName is the Kerberos service name for the Kafka broker
	// (e.g. "kafka").
	ServiceName string
	// Principal is the fully-qualified service principal used by the broker
	// (e.g. "kafka/localhost@EXAMPLE.COM").
	Principal string
}

// RBACConfig describes how to authenticate against a Kafka broker that has
// Confluent MDS (Metadata Service) / RBAC enabled. Clients obtain an
// OAuthBearer token from the MDS token endpoint and present it to the broker.
type RBACConfig struct {
	// MDSURL is the externally reachable MDS HTTP URL (e.g.
	// "http://localhost:8090").
	MDSURL string
	// Principal is the username used to authenticate to MDS.
	Principal string
	// Password is the password used to authenticate to MDS.
	Password string
	// TokenEndpoint is the full URL of the MDS token endpoint
	// (e.g. "http://localhost:8090/security/1.0/authenticate").
	TokenEndpoint string
}
